-- Sylc initial schema. All application data is accessed through Edge Functions using a secret/server key.
-- Browser roles receive no direct table privileges; RLS deny policies are defense in depth.

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null check (char_length(display_name) between 2 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.profile_access_codes (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  lookup_hash text not null unique check (char_length(lookup_hash) = 64),
  verifier_hash text not null check (char_length(verifier_hash) = 64),
  salt text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.provider_credentials (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('openrouter', 'mistral')),
  ciphertext text not null,
  iv text not null,
  status text not null default 'valid' check (status in ('valid', 'invalid', 'unknown')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_validated_at timestamptz,
  unique (profile_id, provider)
);

create table public.profile_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  selected_provider text not null default 'openrouter' check (selected_provider in ('openrouter', 'mistral')),
  selected_model_openrouter text,
  selected_model_mistral text,
  theme text not null default 'light' check (theme in ('light', 'system')),
  temperature double precision not null default 0.7 check (temperature between 0 and 2),
  max_tokens integer not null default 4096 check (max_tokens between 128 and 32768),
  updated_at timestamptz not null default now()
);

create table public.profile_sessions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  token_hash text not null unique check (char_length(token_hash) = 64),
  device_label text not null default 'Unknown device' check (char_length(device_label) between 1 and 120),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'New conversation' check (char_length(title) between 1 and 160),
  provider text not null check (provider in ('openrouter', 'mistral')),
  model_id text not null check (char_length(model_id) between 1 and 240),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('system', 'user', 'assistant')),
  content text not null,
  provider text check (provider is null or provider in ('openrouter', 'mistral')),
  model_id text,
  created_at timestamptz not null default now()
);

create table public.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null check (char_length(scope) between 1 and 80),
  key_hash text not null check (char_length(key_hash) = 64),
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);

create index profile_sessions_profile_idx on public.profile_sessions(profile_id, revoked_at, expires_at);
create index profile_sessions_expiry_idx on public.profile_sessions(expires_at) where revoked_at is null;
create index conversations_profile_updated_idx on public.conversations(profile_id, updated_at desc);
create index messages_conversation_created_idx on public.messages(conversation_id, created_at asc);
create index provider_credentials_profile_idx on public.provider_credentials(profile_id, provider);
create index rate_limit_lookup_idx on public.rate_limit_events(scope, key_hash, created_at desc);
create index rate_limit_created_idx on public.rate_limit_events(created_at);

create or replace function public.consume_sylc_rate_limit(
  p_scope text,
  p_key_hash text,
  p_max integer,
  p_window_seconds integer
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  recent_count bigint;
  event_id bigint;
begin
  if p_max < 1 or p_window_seconds < 1 then
    raise exception 'invalid rate limit configuration';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_scope || ':' || p_key_hash, 0));

  select count(*)
  into recent_count
  from public.rate_limit_events
  where scope = p_scope
    and key_hash = p_key_hash
    and created_at >= now() - pg_catalog.make_interval(secs => p_window_seconds);

  if recent_count >= p_max then
    return null;
  end if;

  insert into public.rate_limit_events(scope, key_hash, succeeded)
  values (p_scope, p_key_hash, false)
  returning id into event_id;

  return event_id;
end;
$$;

revoke all on function public.consume_sylc_rate_limit(text, text, integer, integer) from public;
grant execute on function public.consume_sylc_rate_limit(text, text, integer, integer) to service_role;

create or replace function public.set_sylc_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_sylc_updated_at() from public;
grant execute on function public.set_sylc_updated_at() to service_role;

create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_sylc_updated_at();
create trigger provider_credentials_updated_at before update on public.provider_credentials
for each row execute function public.set_sylc_updated_at();
create trigger profile_preferences_updated_at before update on public.profile_preferences
for each row execute function public.set_sylc_updated_at();
create trigger conversations_updated_at before update on public.conversations
for each row execute function public.set_sylc_updated_at();

alter table public.profiles enable row level security;
alter table public.profile_access_codes enable row level security;
alter table public.provider_credentials enable row level security;
alter table public.profile_preferences enable row level security;
alter table public.profile_sessions enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.rate_limit_events enable row level security;

create policy "deny direct profile access" on public.profiles for all to anon, authenticated using (false) with check (false);
create policy "deny direct access code access" on public.profile_access_codes for all to anon, authenticated using (false) with check (false);
create policy "deny direct credential access" on public.provider_credentials for all to anon, authenticated using (false) with check (false);
create policy "deny direct preference access" on public.profile_preferences for all to anon, authenticated using (false) with check (false);
create policy "deny direct session access" on public.profile_sessions for all to anon, authenticated using (false) with check (false);
create policy "deny direct conversation access" on public.conversations for all to anon, authenticated using (false) with check (false);
create policy "deny direct message access" on public.messages for all to anon, authenticated using (false) with check (false);
create policy "deny direct rate limit access" on public.rate_limit_events for all to anon, authenticated using (false) with check (false);

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.profile_access_codes from anon, authenticated;
revoke all on table public.provider_credentials from anon, authenticated;
revoke all on table public.profile_preferences from anon, authenticated;
revoke all on table public.profile_sessions from anon, authenticated;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
revoke all on table public.rate_limit_events from anon, authenticated;

grant all on table public.profiles to service_role;
grant all on table public.profile_access_codes to service_role;
grant all on table public.provider_credentials to service_role;
grant all on table public.profile_preferences to service_role;
grant all on table public.profile_sessions to service_role;
grant all on table public.conversations to service_role;
grant all on table public.messages to service_role;
grant all on table public.rate_limit_events to service_role;
grant usage, select on all sequences in schema public to service_role;
